### ISSUE TITLE
Code update: explanation

### ISSUE THREAD

**Issue by pv33** [ivapylibs/Surveillance#22]
Code updates that break other peoples code, or without correcting all code involved should be accompanied with an issue that explains what was done and how to resolve the now broken code.

For example ``surveillance/Surveillance/deployment/ROS/testing/rbtScene`` no longer works because some things were changes.  That also means the config file ``surveillance/Surveillance/deployment/ROS/config/testHandTracking01.yml`` is most likely broken.

Please explain here what you did and what needs correction.  Provide successfully modified files as evidence.

I'll try to reverse out edits, but who knows.  Also, make sure to explain what branch is going to be the most correct just in case.

**Comment by yiyeChen** [comment]
The update is about the parameter passing as we discussed last time. Now all the system configurations are put into the yaml file, and needs to be loaded as the ``cfgNode`` from the ``yacs`` library. The other parameters regarding the usage of the system (e.g. ``vis_calib`` controlling the visualization of the calibration process) remain in the ``dataclass`` format object. The ``surveillance/Surveillance/deployment/Base`` class will take both to parse all the information.

The updates are mainly done in the commit b22fef016e9b40c4e0d39b985730703a89726d3a and  995145b092af2e7352222c95c53928c4fd433770. 

I can fix the broken testing scripts by following this paradigm. It will involve using unified parameter names in the yaml file following the ``surveillance/Surveillance/deployment/ROS/config/default.yaml`` example. Also I will need to apply unified argument loading method using the ``yacs``. I wonder whether I am permitted to do this?

My most recent updates are always in the ``yiye`` branch. The updates will be merged into the ``master`` branch either for the required functionalities for the UCF collaborators, or previously combining the efforts from both me and Yunzhi in order to proceed.
