### ISSUE TITLE
Height Estimation parameter update scheme

### ISSUE THREAD

**Issue by yiyeChen** [ivapylibs/Surveillance#4]
Currently the class only use the parameter calculated from the most recent training images. 

To improve the robustness it is better to develop a better parameter update method.

**Comment by pv33** [comment]
This is still kinda crappy, but that's because the depth camera is not as accurate as claimed.  There is non-trivial jitter in the depth values returned for a given pixel location even if nothing changes in the scene. Intel seems to be over-selling their product. Closing because this is kinda known and Yiye's kludge solution had to be used to get it to work.
